### PR TITLE
Update Reaper from 5.963 -> 5.965

### PR DESCRIPTION
**Pull request by wjbuys**
From the [changelog](https://www.reaper.fm/whatsnew.txt):

v5.965 - December 19 2018
  + Arrange: improve vertical scroll behavior on undo, showing/hiding envelopes en masse
  + Audio Units: do not show parameters that are not automatable
  + Audio Units: AU v3 support
  + Audio Units: track parameter IDs across sessions for envelopes/track controls/etc
  + Automation: do not apply envelope trim value to new envelopes when envelopes are bypassed outside of automation items
  + Automation: prevent alt+drag and certain undos from leaving stale envelope panels open [t=192424]
  + Automation: always reset automation-item related options when loading old (pre-automation item) projects
  + Automation: fix undo state point adding for actions that show/hide all envelopes
  + Batch converter: improve updating of output filenames when changing output configuration
  + Comps: include item mute state in addition to active take
  + FX: improve performance of ReaPlugs on x86_64
  + Grid: fix drawing glitches while continuous scrolling
  + JSFX: improve spectrograph/spectrogram preset log scaling
  + JSFX: avoid sometimes setting the 'srate' variable to 0 when plug-in is bypassed [t=214716]
  + JSFX: fix gfx_drawstr() bug with centered mode and bitmapped font [t=214765]
  + JSFX: improve compilation speed of JSFX (2x-10x speedup observed for larger FX)
  + JSFX: improve denormal prevention (for ReEQ and others)
  + JSFX: optimize UI performance for scripts with many regular UI elements visible
  + JSFX: reduce per-instance processing overhead
  + JSFX: use FTZ mode on armv7l
  + Linux: fix excessive video window updates when video stopped
  + MIDI Learn: optionally only respond to learn while effect configuration is visible
  + MIDI Editor: fix ruler theme font issues
  + MIDI Editor: select-all only selects notes within the editable part of a trimmed media item
  + MIDI Editor: fix event position filter [t=213126]
  + MIDI editor: fix synchronization of grid with arrange for "Measure" setting [t=214947]
  + MP3 decoder: show source file channel mode in source properties
  + MP3 encoder: fix gain issue (encoder was incorrectly attenuating signal by 0.0002dB)
  + MP3 encoder: make encoder quality settings consistent with those of command line lame_enc
  + MP3 encoder: add option to prevent joint stereo from being used
  + MP3 encoder: add option to include ReplayGain tag
  + MusicXML: support import of non-ASCII filenames
  + Performance meter: reset RT underrun count/etc when resetting graph via action
  + Preferences: do not search for hidden items on macOS/Linux
  + Preferences: do not show option for 'show last undo in menubar' on macOS [t=214178]
  + Project bay: fix take-selection issues when removing source media from project
  + ReaEQ: update band controls for screen readers [t=213889]
  + ReaScript: IDE add duplicate selected text or current line via Ctrl+D/Cmd+D
  + ReaScript: fix GetSetMediaTrackInfo() for some values on tracks in inactive projects
  + ReaScript: fix gfx_drawstr()/gfx.drawstr() bug with centered mode and bitmapped font [t=214765]
  + ReaScript: improve compilation speed of large EEL scripts
  + ReaScript: optimize calling of extension-defined functions
  + ReaScript: remove limit on size of data returned by GetTrackMIDILyrics()
  + ReaScript: support larger string sizes for extension-defined functions
  + ReaScript: GetSetProjectGrid() can be used to set/get measure mode
  + Recording: respect "tape mode" recording option when auto-punch selected items record mode is enabled
  + Render: auto-saved RPP files when processing render queue rather than when adding to render queue
  + Render: add $bitdepth wildcard
  + Render: allow resizing file overwrite warning window
  + Render: do not auto-save project when using the 'Save and close' button
  + Render: do not prompt for overwrite/missing regions when using 'Save and close' button [p=2059839]
  + Render: support up to 10,000 alternate filenames
  + Render: render wildcards can have character substitions (see built-in help)
  + Takes: improve behavior of next/previous take actions with multiple items selected
  + Takes: improve display vs selection of empty takes
  + Theme: fix redraw of various windows on theme changes
  + Theme: add filter field to theme tweaker to allow searching elements
  + Timecode synchronization: options to re-sync to timecode while recording
  + VST: knob mode changing support for VST3 [t=209071]
  + Video: add Gaussian Blur
  + Video: fix ffmpeg encoder leak
  + Video: fix switching between different display renderers on Windows (DirectShow/generic output)

### CODE REVIEW

**Comment by bspeice** [comment]
Thanks again! It's a bit weird for me to merge and release this though (because Chocolatey thinks everything's already up to date), so how about this: I add you as a maintainer and give you commit access to this repository?

**Comment by bspeice** [comment]
I'm going to go ahead and merge this, but I'm still of the opinion that it makes sense for you to have commit access. Let me know if you're interested.

**Comment by wjbuys** [comment]
Commit access would be appreciated! Also happy to help out with publishing to the choco repo if you're comfortable giving me permissions. Or does that happen automatically on commit?

**Comment by wjbuys** [comment]
Thanks, sounds good! Just let me know what I should configure.

**Comment by bspeice** [comment]
You've been given commit access, just need to let me know what your Chocolatey maintainer name is (and/or register) and you'll be added there as well. I'll be watching my Gitter chat if you have questions!

**Comment by wjbuys** [comment]
Heya, sorry for the delay, been a bit busy. Finally got around to setting up a Chocolatey account, I'm `wjbuys` on there.

**Comment by bspeice** [comment]
Alright, you've been added! My only request is that if you ship a new package you still send a PR here, I want to make sure this repo doesn't get out of sync.

**Pull request merged**
