### PR TITLE
Update reaper to 6.01.

### PR DESCRIPTION
**Pull request by jerome-benoit**
Signed-off-by: Jérôme Benoit <jerome.benoit@piment-noir.org>

### CODE REVIEW

**Comment by bspeice** [comment]
Turns out I had released 6.0, but forgot to update it here. Thanks! For future use - would you like to be added to the contributors who can commit directly?

**Comment by jerome-benoit** [comment]
Hello,

bspeice wrote:
>
> Turns out I had released 6.0, but forgot to update it here. Thanks! 
> For future use - would you like to be added to the contributors who 
> can commit directly?
>

If you don't mind, I'm heavily using reaper, so I will probably react 
quickly on new release.

I have also to check how to become a chocolatey repository contributor, 
I really would like to take over the Tuxguitar maintenance.

Regards,

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bspeice** [comment]
You've been invited to join as a contributor, and once you have a chocolatey account set up, let me know; I'll give you release permissions there as well.

Thanks again!

**Comment by jerome-benoit** [comment]
bspeice wrote:
>
> You've been invited to join as a contributor, and once you have a 
> chocolatey account set up, let me know; I'll give you release 
> permissions there as well.
>

I've pushed the 6.02 reaper update on github (+ minor cleanups on LLVM). 
My account login on the chocolatey packages DB is fraggle.

Can I also push my work on TuxGuitar packaging in the repo ? The 
TuxGuitar co-maintenance is on its way.

Thanks.

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bspeice** [comment]
I guess? It's not a typical way of handling things, but I don't have anything against it.

**Comment by jerome-benoit** [comment]
> Le 19 déc. 2019 à 22:41, bspeice <notifications@github.com> a écrit :
> 
> I guess? It's not a typical way of handling things, but I don't have anything against it.
> 


On the new packages adding?
On the minor changes made on LLVM?

But I can:

* make PRs for new packages;
* make PRs for changes I make on packages I do not maintain directly.

For the sake of reviewing.

It was just convenient to use your setup on that git repo for adding new chocolatey AU packages sources like TuxGuitar or Sonic Visualiser.

I also think I’ve committed a package update on a package I do not maintain but it’s a mistake: I've forgot to put back some files at their initial state after learning how to use the AU tool.

Regards,

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bspeice** [comment]
New packages; my Powershell isn't great, so I'm more than happy to accept changes there.

And all good! You're welcome to make use of the repo, I'll just mention that the setup I have was cloned from [au-packages-template](https://github.com/majkinetor/au-packages-template) if you ever decide to move things into your own repository. Looking forward to having your assistance, I don't use reaper as often as I used to, so help maintaining it is great.

**Comment by jerome-benoit** [comment]
> Le 20 déc. 2019 à 02:34, bspeice <notifications@github.com> a écrit :
> You're welcome to make use of the repo, I'll just mention that the setup I have was cloned from au-packages-template <https://github.com/majkinetor/au-packages-template> if you ever decide to move things into your own repository.
> 
Sharing maintenance with a shared git repository is better than working alone on its own repository. So I see no point of moving things to my own repository, that I will only use for testing purpose.

I will do PRs for new packages I might add in the future.
> Looking forward to having your assistance, I don't use reaper as often as I used to, so help maintaining it is great.
> 
> 

If you give me the rights to push reaper package on chocolatey, I can officially co-maintain it.

++

--
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bspeice** [comment]
Of course. Just let me know what your username is for Chocolatey and I'll get you added as a maintainer.

**Comment by jerome-benoit** [comment]
bspeice wrote:
>
> Of course. Just let me know what your username is for Chocolatey and 
> I'll get you added as a maintainer.
>

I gave it previously: https://chocolatey.org/profiles/fraggle

Thks.

-- 
Jérôme Benoit aka fraggle
Piment Noir - https://piment-noir.org
OpenPGP Key ID : 27B535D3
Key fingerprint : B799 BBF6 8EC8 911B B8D7 CDBC C3B1 92C6 27B5 35D3

**Comment by bspeice** [comment]
I must've missed it. You've been added, let me know if there are any issues.

**Pull request merged**
